### ISSUE TITLE
Add support for Quarkus 3.5

### ISSUE THREAD

**Issue by vsevel** [quarkiverse/quarkus-ironjacamar#57]
I have tried upgrading to Quarkus `3.5.0.CR1` and I get the following error during integration tests:

```
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 1, Time elapsed: 71.43 s <<< FAILURE! -- in io.quarkiverse.ironjacamar.it.InjectionTest
[ERROR] io.quarkiverse.ironjacamar.it.InjectionTest.shouldInjectConnectionFactory -- Time elapsed: 0.022 s <<< ERROR!
java.lang.RuntimeException: java.lang.ExceptionInInitializerError
        at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:639)
        at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:723)
        at java.base/java.util.Optional.orElseGet(Optional.java:364)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.ExceptionInInitializerError
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:467)
        at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:266)
        at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:251)
        at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:606)
        at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:656)
        ... 1 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
        ... 7 more
Caused by: jakarta.enterprise.inject.UnsatisfiedResolutionException: No bean found for required type [class io.quarkiverse.ironjacamar.runtime.secur
ity.QuarkusSecurityIntegration] and qualifiers [[]]
        at io.quarkus.arc.impl.InstanceImpl.bean(InstanceImpl.java:288)
        at io.quarkus.arc.impl.InstanceImpl.getInternal(InstanceImpl.java:309)
        at io.quarkus.arc.impl.InstanceImpl.get(InstanceImpl.java:190)
        at io.quarkus.arc.runtime.BeanContainerImpl.beanInstance(BeanContainerImpl.java:26)
        at io.quarkiverse.ironjacamar.runtime.IronJacamarRecorder.initDefaultBootstrapContext(IronJacamarRecorder.java:69)
        at io.quarkus.deployment.steps.IronJacamarProcessor$initDefaultBootstrapContext1945553743.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.IronJacamarProcessor$initDefaultBootstrapContext1945553743.deploy(Unknown Source)
        ... 8 more
```

cc @gastaldi

**Comment by vsevel** [comment]
caused by https://github.com/quarkusio/quarkus/issues/35744
